language: node_js
sudo: false
node_js:
- '0.10'
before_install:
  npm install -g npm@'>=2.13.5'
before_script:
- npm rebuild
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: payments-devs-automation+npm@mozilla.com
  skip_cleanup: true
  api_key:
    secure: L1yD1CYpeF4likLatL38hFgKZcKcRj6ZXKTtpAHkKTEQBj1dw8/vVzzXpZhJl+zfuNILdeXDRQPJ1+11hMoJUbUnUu8zaTjmijBCxkbrX7P/j2J0RrPxdfHJsoblKxRIAcTif0O/do8PpPHM8RHzxu1bPFiCg+qrwOxFsgr7fJba1MUTUn88icKRh18LNL17y4vjpVHee2TltQ0285PP9LePEnhE/wslY75nG80zCuENF5k2Cyj4l/jhjXjPTv/bsG2PbfEw4I5+qPZVjJ4VcW+nfgJdgv3x0QEuu0yDs1Q+GKQeXizrkHSElSL3ArlCcSTWyfkjWy+SfIN3B47Eu7gi5+EQJIzSt0Wv1BV5CMeKPJKPi3ZkL3JnlCoo+Vra8s85BXU8zzIJrcH6t1UOAAlP0tiW734T2oTkioEgH/eX75aGfDP89sigqQ5L6IlzTtHAmEG5bBg2ICgnvYEgsFCiseSDrmsKkatxgwunnRW8hQ5ZOtJIaPZP25MdfxiOv74z1cEr8H2qhO6wmmtve90xdISBRfqIzOrLIpkxzRxgWu9US4iRy1z9heTQxe7PwTHXhQPu2q+7aKVLcfKEFyUJ14U6ElWtu6exradBAb6Hd0SfUxPIV4XaTaKIUscOH3rYDmJlFfkJRyJyBWcf2MrDZOwP+uxOpyXxSBhHUos=
  on:
    tags: true
    repo: mozilla/payments-client
env:
  global:
  - secure: rBbGQ/SXrTg6hiYsl/tuIeszJe9bMwhmuQPDSuHlZ4zBnLeM1WVGvl4iLQ909OSc3XCjEqXEJatl64yPFdM3bVYMPAdnJg1mlzpF5MVQ7EB/hdvpuV/ghHI7BO4QPOR7G7ERZdK1cLDJALFpAXPyRaoYEmAHS//4Ex7EpEe+MBiurop4NJriXPH7++uOHTPzJE6VKm1S0tbZgjPX97FYsPa/urlT3DYT4b4EP0QNf1oUVQzYIRNnPTb58dNq06MoSMhVS4q2n3PKPLB1KTqcBSl3cIFXlWSsajBmYulh+uN9fpheiEN3vA55SAWcLvfFOO/6w8WHxtd8Pl0wYKV1HpRmU2V8WHcp/0N7mS8b9uPmQ0dLLwuupHRobPHJ4fyHUG4vGmby1em9EAvbPphYxf02QdezOSETbee+3CA7ypszYosz9uRKLVaB6/DYNbjZ1Vw9S2lPJAeBQ82iYVtgDHFQDsM6JuOlDh3nv/oy6ro25mAAa2bEFKnaIL0IYvN9rPI/JwRL3O2Q1mXL3EXoHBZz8zXmfaPK/c3dmreBSke/Y8tfHSM7QOw0OTeQuPutAX8rmOdilpBSKnF/RzaPuaVwFzOxYXco3nwMKw4ikoDORjvS8fhfMaShcaKxC4Be16CwZn/iXWJ/l2egGqeEbawUsRVQj/x7a1t1UoWNVso=
  - secure: uwP4djcQZg3NlDZUCctpfWrS7DHqc0pJ3TVETHvH1/mWbkNagFJYV86zOmc3YP8mDg+I2VvKjDw7/ZwNV+sY15NXOnIhSuFjPv+1AazCoaGo0CMTHKshw3Q3XnpnPkv19LdyCSBI5AKVxCt3mac7M6oQGfyGkTbLJXc+rO8DacAnmH2APousrBG5ERwR/+Kf2TGdsT5ld60t8eo9grYDL03xuqaLUM10z/CBM2E8GgMwny97ZoCs3cdG5EvanmJJbxLSbWwx2zvYrkUeuymXbqAPxUtgkDsxDKwZIy2/+U/gWfpPFClsrtVNPI+WwaotvZ68barLGdVKW6ZDg1FlJCUE8+Tv7yYD0CtmRrO28+xtnPFtCUTKNytrX4OTs5HYYSad9F9E5F1k3UntnvSukpjjAsNcqfvg3ZQe6CiINKRthR8u/N5RK/cNaZaG67zD7cn3R/Zn/V2VJ0OUUl2DTezPnaflctaQKqn13t1JQ/3GiE6GPKtcrRYr0NIGWstJl5QbRFp6Ta7E01suzKlTKgoQlNNlh+4uiq3wEWOl2bPNLMyMgJB96w/6+QuKwYME9wvl4ZSDKcYY3QWIhrsVUJNtNfaUYhqHAwpkB0ifOH+HY84wes2WcK93xxTmDoB6SbQvVLTiG5qDU0B/3MEZmLcgDI5/r7/Yd8pVPMQfvzY=
