language: node_js
sudo: false
node_js:
- '0.10'
before_script:
- npm rebuild
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: payments-devs-automation+npm@mozilla.com
  skip_cleanup: true
  api_key:
    secure: L1yD1CYpeF4likLatL38hFgKZcKcRj6ZXKTtpAHkKTEQBj1dw8/vVzzXpZhJl+zfuNILdeXDRQPJ1+11hMoJUbUnUu8zaTjmijBCxkbrX7P/j2J0RrPxdfHJsoblKxRIAcTif0O/do8PpPHM8RHzxu1bPFiCg+qrwOxFsgr7fJba1MUTUn88icKRh18LNL17y4vjpVHee2TltQ0285PP9LePEnhE/wslY75nG80zCuENF5k2Cyj4l/jhjXjPTv/bsG2PbfEw4I5+qPZVjJ4VcW+nfgJdgv3x0QEuu0yDs1Q+GKQeXizrkHSElSL3ArlCcSTWyfkjWy+SfIN3B47Eu7gi5+EQJIzSt0Wv1BV5CMeKPJKPi3ZkL3JnlCoo+Vra8s85BXU8zzIJrcH6t1UOAAlP0tiW734T2oTkioEgH/eX75aGfDP89sigqQ5L6IlzTtHAmEG5bBg2ICgnvYEgsFCiseSDrmsKkatxgwunnRW8hQ5ZOtJIaPZP25MdfxiOv74z1cEr8H2qhO6wmmtve90xdISBRfqIzOrLIpkxzRxgWu9US4iRy1z9heTQxe7PwTHXhQPu2q+7aKVLcfKEFyUJ14U6ElWtu6exradBAb6Hd0SfUxPIV4XaTaKIUscOH3rYDmJlFfkJRyJyBWcf2MrDZOwP+uxOpyXxSBhHUos=
  on:
    tags: true
    repo: mozilla/payments-client
