language: node_js
sudo: false
node_js:
- '0.10'
before_script:
- npm rebuild
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test
after_success: npm run-script publish-release > /dev/null 2>&1
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
env:
  global:
  - secure: ZTmlQcF836j19c0XNGcjL1QPaZCOiaHKT4MTkhTspHdqcZoyPsPKvBB+wivAVR4DEN8qq3wfqtBDPUfqoTgK9fqbFFHHF8Vl0pgBePyd57XEjQ1oSNwPLycr6Q0cO4sw+LC0tq1zbiREawTH5VV2101Y3yawm+TNWQqMZT/YTOKlqmF0V5+oq4xAfurJqz+Q+0TAM7ciXG2u4w2SKO/qLIv+pA9Fkb92FNjS5MMRDwcAtAwdxHEOsPS2FhyBR0mg+zofN5EjHQ+FZnLTecGrjnF3Dyv4sXRWI2qO0xlTeotbEfdZzw/xZ9so0T4jzQ1alRNrNYBXIVYbTin2izqjJi/vUZrme4G3zNFN81GC4U0nvzUAY0MQNAdzOPZdu6i7to/aUPlBc+VXbcq4yBr/vBD1Jpn4xjGvkORBQ2UjRIpEZUrd3lMTXt79lRTOL8nN4sc5viula/2NfSSwcHI4lhHBR1ypF20hMXoTUFeZk1PtZOgzTUcQ9WC4AqE9TQ/ZBuyOiE4y3MNaB3NhqMl3KW+8ACE64/Tk0ni6VeeNuL+i46Mwe7Q6wVo0WRaWDYe68c7yXZ7zjGtIWijjbXtr5rN5/GRf3spmGllo+xWK2CY414lv29K/ikbkVV818d389QA5HCCTZt8LXfZJOIFcJSGxj1gMm6rEznwL3wRAsKc=
  - secure: dZ6iVq97A1gtTPh53mjHQ4TwXcfH4yOPDnXQQmZFWymFyQzfVgYwbTuJB0uoz9OGrdrTH/2BK2n9gNqm4huidum9HVjfZ6EUft72AGiH0U7cUmHlIJJ1Jk5nTY+vIpO6WfU2xjn0brRZ7KovcciKC12bz3/cWrhCM9afHBhJ+CXie2N/tGCTW4KkRfZM1u0/psWMLuJvPRPCrlGQ7fg3rLdmNq5zST+rMBrCUJX29mFvHDhVMpj01IG4/LmXcJcAbeeXtmDnyJ2+P2fpLkTkZKNDLKeMzzm7v5+6QWlrhVIaM28pDHZM3i8hBju6Qd0ruS44t2mmCgVrq+WIsg+/LOrnWZMACFcPWWyrZo8sguAcxiC6UA6YfjFyPZxURQIfSj11aArqbfNEjwosv0yThcqx67HHjO2ugm3aKiXtlKJXIldPTHWkYyzQCXTSTa8YDnKLcyxS2htw53zZOYNsgheaAxkPkzwbDa7O99TGCAdWkt21on3yibOeVEwTITqhEvPR2cd5nqFKep6Og5osh4PzFIJ0MgTsKCgspdSdVuFFI7wYgNw5PwOqLkkygpBS5jr+yoeyFBGKDzArAztDBaZBIwG7MjGa1Ai1vKLzEeW1yt1arVMURV8KwVzWeEbk3hQHJD19bZandm4rVZLDnmBO+IxOh5H9ntsGR1kFt04=
  - secure: 0PEXxgKRFfsw/8NpyZyrBkVgOn+NxDCZrhUfV4h5H+1vqZWXNmNeNqTAQsXL1aq0N6ZERdpbOHeE71dXydL+Vj3KUEktzHEoZ7sbtILMcTBe6nRuAVnf5YHjpyKh1xWrKdUAF05GYaqfrUWXb9po+p/pR+Ogjz1t3HVEgJk+bgY6aBI6X5+4feOT+o2jnuVyz/DYX8bXOAvWrBwKKH+H7hUGB0vh3iP0A5NXln5h7HGgrMj329VmxXpyiqW/0sMn3DBAMvRVbEW8SXbtnCUM7VSnR/soUdmvf1EJGLERY1GXGslQsE/o6SBHJ9kgJQIcAQhh1NDv9toKeOpFcjqPIsAQPbBeeCuu9kdxU0YV7zWvxacS3jj+aTqrbLE+EfvNt5Y3CGcyacjmNBmg6oDoz8/Xcuk9rfPIQ5sWzh9GSVGxcBckS647mNlumLqp8+gqmqLJWgxEOzBzlu6m51N2D/X7NANbEdh7NWSXlbhq89aQ2oibfmpMl41WXfonqdm/9EqwOvSk6gYsVcseF1BQH0f9gu8LbaC6pW8UqhTfnk19EXV04qkDOOFPTz74HLtsdKtf96wsOJtW3XBveEkeovS+cC5K8WRErc5+qesAK29SSeT93P1FifYqPq/QKAkfHyLJsogTGNFjeAkEKRz9lH7XFlFQ/jDdtLVTyS8Rq0U=
